# Generated by Django 3.2.4 on 2021-06-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_list',
            old_name='is_active',
            new_name='is_in',
        ),
    ]
